on:
  push:
    branches:
     - main

name: Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
      - name: Preparing production environment
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mkdir public
          cp -r dist/xtreme-admin-angular/* public
          
          rm -rf dist
          rm -f *.json
          rm -f *.js
          
          mv dokku/* .
          ls -l
          git status
          cat package.json
          cat index.js
          
          git add .
          git commit -m "Setting up production environment"
          git remote add dokku dokku@cluster-ig4.igpolytech.fr:cuisinedu-back
          echo ${{ secrets.SSH_PRIVATE_KEY }} > /home/.ssh/id_rsa
          cat /home/.ssh/id_rsa
          git push dokku --force
